#插件前缀
PluginPrefix: '&9[&b&lCN2B2T&c&lCore&9]'

ChatCoolDown:
  ChatLimit: true
  LimitTime: 3 #second
  NotifyMessage: "&c聊天冷却中..."

WindowClickCheck:
  check: true
  count: 20

PacketFlyCheck:      # 反作弊 检测packetfly
  ClassicCheck: true
  NewStrictCheck: true

#水晶限速 depend: ProtocolLib
CrystalSpeedLimit:
  limit: true
  BreakDelay: 30 #millisecond 尽量不要太高

Dupes:
  ShulkerDupe:  #↓ 启用潜影盒免费刷物品，表示10+1，暂未实现
    enable: true
    count: 10
  DoubleDonkey:   #↓ 启用驴刷，暂未实现
    enable: true
  SuperChicken:   #↓ 启用鸡刷，暂未实现
    enable: true
